# This workflow sync the current github repo to a remote repo by using 'git push'.

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push to remote repo
        uses: michaelliao/git-push-action@v3
        env:
          PUSH_SSH_KEY: ${{ secrets.PUSH_SSH_KEY }}
        with:
          remote_repository: |
            git@gitlab.com:cryptomichael/liaoxuefeng.com.git
            git@gitee.com:liaoxuefeng/liaoxuefeng.com.git
          push_options: "--force"
